In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.style.use('seaborn-darkgrid')

In [2]:
df = pd.read_csv('../../data/data.csv', index_col=0)
df.head()

,HouseholdID,Real,Reentered,ES,PSH,TH,RRH,PREV
1,2028039,2,0,0.425008,0.271801,0.350017,0.397626,0.291637
2,2036520,2,0,0.327550,0.188743,0.266543,0.337444,0.218234
3,2108682,2,0,0.186973,0.760772,0.137805,0.178759,0.106168
4,2116994,2,0,0.234827,0.217690,0.183896,0.239388,0.148293
5,2154639,2,0,0.299406,0.554693,0.232651,0.265632,0.190321

In [3]:
households = [i for i in range(1, df.shape[0])]
types = ['ES', 'PSH', 'TH', 'RRH', 'PREV']

In [4]:
optimal_df = pd.read_csv('../../data/optimal.csv', index_col=0)
optimal_df.head()

    ES  PSH   TH  RRH  PREV
1  1.0  0.0  0.0  0.0   0.0
2  1.0  0.0  0.0  0.0   0.0
3  0.0  0.0  1.0  0.0   0.0
4  0.0  0.0  0.0  0.0   1.0
5  0.0  0.0  0.0  0.0   1.0

In [ ]:
# To be 
def fairness(assignment_df):
    return np.max(df['Reentered'] - np.array([
        sum(assignment_df.loc[household, type_] * df.loc[household, type_] 
            for type_ in types) 
        for household in households
    ]))